testTraces <- function(Traces){
	message("are the subtable names correct?")
	all(names(Traces) == c("traces", "trace_type", "trace_annotation", "fraction_annotation"))
	message("are the subtable classes correct")
	all(class(Traces$traces) == c("data.table", "data.frame"))
	all(class(Traces$trace_annotation) == c("data.table", "data.frame"))
	all(class(Traces$fraction_annotation) == c("data.table", "data.frame"))
	message("nrow(Traces$traces) == nrow(Traces$trace_annotation)")
	all(nrow(Traces$traces) == nrow(Traces$trace_annotation))
	message("names(traces)[ncol(Traces$traces)] == id")
	all(names(Traces$traces)[ncol(Traces$traces)] == "id")
	message("are the traces names equal to fraction annotation id column")
	all(names(Traces$traces)[seq(1, ncol(Traces$traces)-1)] == Traces$fraction_annotation$id)
	message("are the traces ids equal to trace_annotation id column")
	all(Traces$traces$id == Traces$trace_annotation$id)
	message("are all the trace id columns character")
	all(class(Traces$traces$id) == "character")
	all(class(Traces$trace_annotation$id) == "character")
	message("are all the fraction id columns numeric")
	all(class(Traces$fraction_annotation$id) == "numeric")
  }
